name: Deploy React Vite App to Azure Web App - Edetailmednet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Node 20 is LTS, recommended version for Vite apps

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A542708D9B91455FA7A360F1DA598405 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3CCA8748C74E41348DCF1D6B10C90036 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A0F6CBFC853B40B9BB19B2315AED168B }}

      - name: 'Deploy dist to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Edetailmednet'
          slot-name: 'Production'
          package: dist
